### PR TITLE
Misc improvements & resolve open issues

### PR DESCRIPTION
**Pull request by oliviernotteghem**
- Disable search menu entry when no text is selected.
- Fix handling of local branch
- Move menu entries into sub-menu
- Implement copy link functionality
- Use Project storage API to load config from

### CODE REVIEW

**Comment by slimsag** [comment]
Apologies for the delay on this, I’ll review and merge soon!

**Comment by slimsag** [comment]
Thanks for the PR @oliviernotteghem -- this is really cool, I especially like the icon and submenu! I pushed some minor changes here: https://github.com/sourcegraph/sourcegraph-jetbrains/pull/14

One problem with this approach.. I notice this doesn't appear in the editor preferences UI which is what https://github.com/sourcegraph/sourcegraph-jetbrains/issues/11 and https://github.com/sourcegraph/sourcegraph-jetbrains/issues/7 seem to indicate we should be doing.

It seems this just changes the configuration from a manual `$HOME/sourcegraph-jetbrains.properties` that one must write to a `.idea/sourcegraph.xml` that one must write (also with no nice uI or editor support)

I think we need to do something like this: http://corochann.com/intellij-plugin-development-introduction-applicationconfigurable-projectconfigurable-873.html#Making_classimplements_Configurable

I would merge this as-is, because the bug fixes are good, but one problem sticks out to me with this approach in particular:

`.idea/sourcegraph.xml` is in a single project only, while `$HOME/sourcegraph-jetbrains.properties` is at least global. Since most users will only interact with a single Sourcegraph instance, it seems bad to make them configure the Sourcegraph URL for each project. What do you think?

**Comment by oliviernotteghem** [comment]
Hi Stephen
This totally makes sense. How about we have a quick meeting over Zoom to discuss this early this week?
Also, there is another issue I need to fix, however I’d need some guidance from you- in brief, for search actions, the current repo is ignored, i.e it searches against the entire set of repo in sourcegrap.
Oli.

**Comment by slimsag** [comment]
Yeah, I'd love to! I could do the following times:

- Tue 12 PM - 2 PM PST 
- Wed 11AM - 4PM PST

Do either of those work for you? If yes just send me an invite to stephen@sourcegraph.com

**Comment by slimsag** [comment]
>  in brief, for search actions, the current repo is ignored, i.e it searches against the entire set of repo in sourcegrap.

I think we could solve this by having two actions: "Search" (global) and "Search in repository"

Only question is: could we come up with another keyboard shortcut that makes sense? Maybe Option+R ?

This change will also require a change [on the Sourcegraph.com side](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b52275616a60c661e5c8ec8e27d3fc9f22bd4bc5/-/blob/cmd/frontend/internal/app/editor.go) so that `repo:$THE_REPO` gets added to the search query, but should be easy enough to do and I can make that.

**Comment by oliviernotteghem** [comment]
Perfect! Sent you an invite for 12-12.45 tomorrow!

**Comment by slimsag** [comment]
Hey @oliviernotteghem I am working on:

- Adding the `Search in repository` action we mentioned, I am thinking alt+r as a shortcut for that -- any objection to that?
- Do you have any example `.idea/sourcegraph.xml` configuration? I took a look for a few hours but wasn't able to decipher exactly what `PersistentStateComponent<Config>` expects - I am sure I am just missing something obvious here but could you give me a pointer?

**Comment by slimsag** [comment]
@oliviernotteghem any chance you could take a quick look at my last message? I'd love to land this soon

**Comment by oliviernotteghem** [comment]
Sorry, I somehow missed it. .idea/sourcegraph.xml will be generated automatically whenever you close project / IDE, provided you specific data. So just invoke setter (instead of getter) in your code, run it, close IDEA, and you should see the file.

for the shortcut key combo : sounds good to me.

**Comment by slimsag** [comment]
Merged via https://github.com/sourcegraph/sourcegraph-jetbrains/pull/14

**Pull request closed without merging**
